excluded:
- Pods
- DerivedData
disabled_rules: # rule identifiers turned on by default to exclude from running
- colon
- trailing_whitespace
- nesting
- comment_spacing

large_tuple: 3

line_length:
 warning: 300
 error: 500

function_body_length:
 warning: 40
 error: 70

type_body_length:
 warninig: 200
 error: 400

