# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'Seminar2_HW2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SwiftLint'

  # Pods for Seminar2_HW2

end
